version: 2.1
jobs:
  package: 
    docker: 
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
         keys:
           - pkg
      - run:
          name: Checkout
          command: |
            ./make.sh CHECKOUT
      - save_cache:
          key: pkg
          paths:
            - ./UnityPackage
      - run:
          name: Package
          command: |
            ./make.sh PACKAGE
      - save_cache:
          key: pkg
          paths:
            - ./UnityPackage
      - run:
          name: Index
          command: |
            ./make.sh INDEX
      - save_cache:
          key: pkg
          paths:
            - ./UnityPackage
      - run:
          name: Push
          command: |
            cd ./UnityPackage
            git config credential.helper 'cache --timeout=120'
            git config user.email "oparaskos@gmail.com"
            git config user.name "Deployment Bot"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://${PACKAGE_GITHUB_TOKEN}@github.com:oparaskos/com.github.umasteeringgroup.uma.uma.git -f -u origin HEAD
      - save_cache:
          key: pkg
          paths:
            - ./UnityPackage
workflows:
  package:
    jobs:
      - package
